// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quwqigismycdknmyhgte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1d3FpZ2lzbXljZGtubXloZ3RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDUyMDAsImV4cCI6MjA3MzkyMTIwMH0.zO-zM4hJn_858kAn3O5B-878P2hp3KlRR1pS6RrSZaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});